#####
name: P2p
noise_level: 1.0  #  noise level
save_root: '/home/ftahmed/Reg-GAN/NC+R/model_L2/'
image_save: '/home/ftahmed/Reg-GAN/NC+R/img_L2/'
train_image: '/home/ftahmed/Reg-GAN/NC+R/Train_image/'

# lamda weight
GenAdv_lamda: 1.
DisAdv_lambda: 1.
P2P_lamda: 100.


epoch: 0        # starting epoch
n_epochs: 80       # How often do you want to display output images during training
batchSize: 1               # size of the batches
dataroot:  '/home/ftahmed/Reg-GAN/data/train2D/'      # root directory of the 
# dataroot: '/home/ftahmed/amlcourseproject/MICCAI_Training/HGG'
val_dataroot:  '/home/ftahmed/Reg-GAN/data/val2D/'
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 256                # size of the data crop
input_nc: 1         
output_nc: 1                  
cuda: True                
# n_cpu: 1

